const PRIVILEGE_SETTINGS_KEY='kidBehaviour_privileges_v1';
function loadCustomPrivileges(){try{const saved=JSON.parse(localStorage.getItem(PRIVILEGE_SETTINGS_KEY));if(Array.isArray(saved))state.privileges=saved}catch{};state.privileges=state.privileges.map(p=>({...p,active:p.active!==false}));}
function saveCustomPrivileges(){localStorage.setItem(PRIVILEGE_SETTINGS_KEY,JSON.stringify(state.privileges));save();}
loadCustomPrivileges();
let privilegeEditor=null;
const originalSettingsPage=settingsPage;
settingsPage=function(){return `<section class="panel"><h2>Niños</h2>${state.children.map(c=>`<div class="setting-row"><span>${c.emoji} ${c.name}</span><strong>${c.age} años</strong></div>`).join('')}</section><section class="panel"><div class="priv-title"><div><h2>Privilegios</h2><p>Modifica los privilegios que utilizáis en casa.</p></div><button class="priv-add" data-priv-add>+ Añadir</button></div>${state.privileges.map(p=>`<div class="priv-setting"><div><strong>${p.icon||'🎁'} ${escapeHtml(p.name)}</strong>${p.active===false?'<small>Inactivo</small>':''}</div><div class="priv-actions"><button data-priv-toggle="${p.id}">${p.active===false?'Activar':'Desactivar'}</button><button data-priv-edit="${p.id}">Editar</button><button class="priv-delete" data-priv-delete="${p.id}">Eliminar</button></div></div>`).join('')||'<p>No hay privilegios configurados.</p>'}</section><section class="panel"><h2>Datos</h2><p>Los datos se guardan solo en este dispositivo.</p><button class="danger" data-reset>Vaciar histórico</button></section>`};
const originalModalHtml=modalHtml;
modalHtml=function(){const base=originalModalHtml();if(!privilegeEditor)return base;const p=privilegeEditor.id?state.privileges.find(x=>x.id===privilegeEditor.id):null;return base+`<div class="overlay priv-overlay"><div class="sheet priv-sheet"><div class="sheet-head"><div><h2>${p?'Editar privilegio':'Nuevo privilegio'}</h2><p>Elige un icono y un nombre.</p></div><button data-priv-close>✕</button></div><label>Icono<input id="privIcon" maxlength="4" value="${escapeHtml(p?.icon||'🎁')}"></label><label>Nombre<input id="privName" maxlength="50" value="${escapeHtml(p?.name||'')}" placeholder="Ej. Elegir película"></label><button class="primary" data-priv-save>${p?'Guardar cambios':'Añadir privilegio'}</button></div></div>`};
const originalWire=wire;
wire=function(){originalWire();document.querySelector('[data-priv-add]')?.addEventListener('click',()=>{privilegeEditor={id:null};render()});document.querySelectorAll('[data-priv-edit]').forEach(b=>b.onclick=()=>{privilegeEditor={id:b.dataset.privEdit};render()});document.querySelectorAll('[data-priv-toggle]').forEach(b=>b.onclick=()=>{const p=state.privileges.find(x=>x.id===b.dataset.privToggle);if(p){p.active=p.active===false;saveCustomPrivileges();render()}});document.querySelectorAll('[data-priv-delete]').forEach(b=>b.onclick=()=>{const p=state.privileges.find(x=>x.id===b.dataset.privDelete);if(p&&confirm(`¿Eliminar “${p.name}”?`)){state.privileges=state.privileges.filter(x=>x.id!==p.id);Object.values(state.days).forEach(d=>d.lostPrivileges=(d.lostPrivileges||[]).filter(id=>id!==p.id));saveCustomPrivileges();render()}});document.querySelector('[data-priv-close]')?.addEventListener('click',()=>{privilegeEditor=null;render()});document.querySelector('[data-priv-save]')?.addEventListener('click',()=>{const name=document.getElementById('privName').value.trim(),icon=document.getElementById('privIcon').value.trim()||'🎁';if(!name){alert('Escribe un nombre para el privilegio.');return}if(privilegeEditor.id){const p=state.privileges.find(x=>x.id===privilegeEditor.id);p.name=name;p.icon=icon}else state.privileges.push({id:`priv_${Date.now()}`,name,icon,active:true});saveCustomPrivileges();privilegeEditor=null;ui.toast='Privilegios actualizados ✓';render();setTimeout(()=>{ui.toast=null;render()},1800)});};
render();